# Generated by Django 4.0.3 on 2023-02-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greet',
            old_name='content_k',
            new_name='dohui',
        ),
        migrations.RenameField(
            model_name='greet',
            old_name='content_p',
            new_name='gyeongjun',
        ),
        migrations.RenameField(
            model_name='greet',
            old_name='content_s',
            new_name='huigwan',
        ),
        migrations.RenameField(
            model_name='greet',
            old_name='content_j',
            new_name='jiwon',
        ),
        migrations.RenameField(
            model_name='greet',
            old_name='content_m',
            new_name='sunah',
        ),
        migrations.RenameField(
            model_name='greet',
            old_name='content_c',
            new_name='woojin',
        ),
        migrations.RenameField(
            model_name='greet',
            old_name='content_h',
            new_name='yeeun',
        ),
    ]
