# Generated by Django 4.0.3 on 2023-03-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greet', '0002_rename_content_k_greet_dohui_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greet',
            name='dohui',
        ),
        migrations.RemoveField(
            model_name='greet',
            name='gyeongjun',
        ),
        migrations.RemoveField(
            model_name='greet',
            name='huigwan',
        ),
        migrations.RemoveField(
            model_name='greet',
            name='jiwon',
        ),
        migrations.RemoveField(
            model_name='greet',
            name='sunah',
        ),
        migrations.RemoveField(
            model_name='greet',
            name='woojin',
        ),
        migrations.RemoveField(
            model_name='greet',
            name='yeeun',
        ),
        migrations.AddField(
            model_name='greet',
            name='cha',
            field=models.TextField(blank=True, null=True, verbose_name='김재우'),
        ),
        migrations.AddField(
            model_name='greet',
            name='cho',
            field=models.TextField(blank=True, null=True, verbose_name='조성민'),
        ),
        migrations.AddField(
            model_name='greet',
            name='cwj',
            field=models.TextField(blank=True, null=True, verbose_name='정우진'),
        ),
        migrations.AddField(
            model_name='greet',
            name='hye',
            field=models.TextField(blank=True, null=True, verbose_name='홍예은'),
        ),
        migrations.AddField(
            model_name='greet',
            name='kim',
            field=models.TextField(blank=True, null=True, verbose_name='김강민'),
        ),
        migrations.AddField(
            model_name='greet',
            name='kye',
            field=models.TextField(blank=True, null=True, verbose_name='김예은'),
        ),
        migrations.AddField(
            model_name='greet',
            name='kyk',
            field=models.TextField(blank=True, null=True, verbose_name='김윤경'),
        ),
        migrations.AddField(
            model_name='greet',
            name='min',
            field=models.TextField(blank=True, null=True, verbose_name='조민솔'),
        ),
        migrations.AddField(
            model_name='greet',
            name='one',
            field=models.TextField(blank=True, null=True, verbose_name='원동현'),
        ),
        migrations.AddField(
            model_name='greet',
            name='sim',
            field=models.TextField(blank=True, null=True, verbose_name='심재성'),
        ),
        migrations.AddField(
            model_name='greet',
            name='yes',
            field=models.TextField(blank=True, null=True, verbose_name='임예람'),
        ),
    ]
