# Generated by Django 4.0.3 on 2022-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student1_value1',
            field=models.CharField(max_length=8, null=True, verbose_name='추천1 가치1'),
        ),
        migrations.AddField(
            model_name='user',
            name='student1_value2',
            field=models.CharField(max_length=8, null=True, verbose_name='추천1 가치2'),
        ),
        migrations.AddField(
            model_name='user',
            name='student1_value3',
            field=models.CharField(max_length=8, null=True, verbose_name='추천1 가치3'),
        ),
        migrations.AddField(
            model_name='user',
            name='student2_value1',
            field=models.CharField(max_length=8, null=True, verbose_name='추천2 가치1'),
        ),
        migrations.AddField(
            model_name='user',
            name='student2_value2',
            field=models.CharField(max_length=8, null=True, verbose_name='추천2 가치2'),
        ),
        migrations.AddField(
            model_name='user',
            name='student2_value3',
            field=models.CharField(max_length=8, null=True, verbose_name='추천2 가치3'),
        ),
    ]
