# Generated by Django 4.0.3 on 2023-03-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_grade_alter_user_leader_alter_user_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student1_intro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student1_value1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student1_value2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student1_value3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student2_intro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student2_value1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student2_value2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student2_value3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='value',
        ),
        migrations.AddField(
            model_name='user',
            name='student3',
            field=models.CharField(max_length=8, null=True, verbose_name='팀원3'),
        ),
        migrations.AlterField(
            model_name='user',
            name='leader',
            field=models.CharField(max_length=8, null=True, verbose_name='팀장'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student1',
            field=models.CharField(max_length=8, null=True, verbose_name='팀원1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student2',
            field=models.CharField(max_length=8, null=True, verbose_name='팀원2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='track',
            field=models.CharField(choices=[('개발', '개발'), ('백엔드', '백엔드'), ('프론트엔드', '프론트엔드'), ('기획디자인', '기획디자인')], max_length=18, null=True, verbose_name='트랙'),
        ),
    ]
