# Generated by Django 4.0.3 on 2023-03-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_interest_remove_user_modifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student3',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='팀원3'),
        ),
    ]
