# Generated by Django 4.0.3 on 2023-03-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_teammanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammanager',
            name='department',
            field=models.TextField(blank=True, null=True, verbose_name='학과'),
        ),
        migrations.AddField(
            model_name='teammanager',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='연락처'),
        ),
    ]
