# Generated by Django 4.0.3 on 2022-03-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=17, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=256, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=8, null=True, verbose_name='이름')),
                ('modifier', models.CharField(max_length=8, null=True, verbose_name='수식어')),
                ('department', models.CharField(max_length=24, null=True, verbose_name='학과')),
                ('grade', models.CharField(choices=[('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년'), ('4학년', '4학년'), ('5학년', '5학년'), ('졸업생', '졸업생')], max_length=18, null=True, verbose_name='학년')),
                ('track', models.CharField(choices=[('백엔드', '백엔드'), ('프론트엔드', '프론트엔드'), ('기획/디자인', '기획/디자인')], max_length=18, null=True, verbose_name='트랙')),
                ('leader', models.CharField(max_length=8, null=True, verbose_name='리더')),
                ('value', models.CharField(max_length=8, null=True, verbose_name='가치')),
                ('interest', models.CharField(max_length=8, null=True, verbose_name='관심사')),
                ('level', models.CharField(choices=[('2', 'LV2_아기사자'), ('1', 'LV1_운영진'), ('0', 'LV0_개발자')], default=2, max_length=18, verbose_name='등급')),
                ('student1', models.CharField(max_length=8, null=True, verbose_name='추천1')),
                ('student1_intro', models.TextField(max_length=256, null=True, verbose_name='추천1 설명')),
                ('student2', models.CharField(max_length=8, null=True, verbose_name='추천2')),
                ('student2_intro', models.TextField(max_length=256, null=True, verbose_name='추천2 설명')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': '회원목록',
            },
        ),
    ]
